name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main

jobs:
  # Job to deploy Firebase Hosting (runs on every push)
  deploy_hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project ${{ secrets.GCP_PROJECT_ID }}

  # Job to deploy Cloud Functions (only runs when 'functions/' changes)
  deploy_functions:
    runs-on: ubuntu-latest
    if: github.event.push.before != github.event.push.after && contains(github.event.commits.*.added, 'functions/') || contains(github.event.commits.*.modified, 'functions/') || contains(github.event.commits.*.removed, 'functions/')
    needs: deploy_hosting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: registerUserProfile
          runtime: python311
          entry_point: registerUserProfile
          source_dir: 'functions'
          project_id: ${{ secrets.GCP_PROJECT_ID }}